plugins:

  cfy_util: &utilities_plugin
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.4.0.zip
    package_version: '1.4.0'

  cfy_files: *utilities_plugin

  cloudify_custom_workflow: *utilities_plugin

  cloudinit: *utilities_plugin

  configuration: *utilities_plugin

  keys: *utilities_plugin

  suspend: *utilities_plugin

  terminal: *utilities_plugin
